### ISSUE TITLE
Add cake-contrib user

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Board#32]
First of all, I wanted to thank you for adding to the Cake community by adding this addin.

I was just wondering if you had seen this blog post:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

We are currently going through a process of increasing the visibility of addins, and also trying to ensure their long term maintainability.

To that end, we are asking addin creators to add the cake-contrib user on NuGet as a co-owner (this can be done through the NuGet website by clicking on Manage Owners on the package page).

Would you be interested in doing this? If you have any questions about this, please let me know. There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

Thanks!

**Comment by nicolabiancolini** [comment]
Hi @gep13, sorry for the late response.
No I had not read the post in the blog since now a little dated. :(

I invited the cake-contrib user as a co-owner in the NuGet packages.
Let me know if I can close this issue or if there is anything else.

Thanks!

**Comment by gep13** [comment]
@nicolabiancolini that is great!  Thank you for taking the time to do that, I appreciate it!

In terms of the original idea behind this raising this issue, it can be closed, however, I do have a follow up question...

I have been encouraging more addin maintainers to move their repositories under the Cake Contrib Organisation on GitHub, that way should something happen, the Cake Contrib Community are then in a better position to help with the on-going maintenance of the addins.  Is this something that you would consider doing?

Please let me know if you have any questions.

**Comment by nicolabiancolini** [comment]
Sounds like a good idea to me.

How do you usually proceed?

I need the necessary permissions to create branch policies in order to ensure the proper work of the CI processes. Is it possible to have them?

**Comment by gep13** [comment]
The process for moving repositories into the Cake-Contrib Organisation is listed here:

https://github.com/cake-contrib/Home#how-do-i-as-an-addin-author-transfer-a-repository-to-the-organisation

Where only the first step would need to be completed by yourself, i.e. transferring them to my GitHub account, and from there, I would transfer them into the Organisation.  This is a limitation of GitHub.

Once transferred, you would have full admin permissions on the repositories, in the same way as you do now, so you should be able to apply any settings that you feel are required.

**Comment by gep13** [comment]
@nicolabiancolini I have completed the transfer of the repository to the Cake Contrib Organisation, and I have sent you an invite to join the Organisation.

Do you use Twitter and Slack? If so, can you let me know the details to use?  We have a Slack Team which is used by the Cake Contrib maintainers for asking any questions about anything.

Please let me know if you have any questions.
